### ISSUE TITLE
LAMMPS input order -> tail correction lost after restart

### ISSUE THREAD

**Issue by fuulish** [agiliopadua/fftool#1]
Dear Agilio Padua,

I have been using fftool for preparing my MD simulations with LAMMPS. I recently fell prey to an unexpected effect due to the order of directives in the LAMMPS input scripts generated by fftool.
If one uses pair_style hybrid, the pair_modify settings (e.g., tail correction) don't seem to be stored in the binary restart file. This will lead to an unexpected, yet significant, drop in the density in a simulation.

I have submitted the issue to the LAMMPS-users mailing list (see link below), but it is yet unclear whether this is going to be resolved internally in LAMMPS. To avoid any possible issues and confusion I would suggest changing the order of the restart and pair_style/pair_modify directives in the LAMMPS input generation in fftool.

If you want I can create a corresponding pull request.

Cheers,

Frank

inquiry to the LAMMPS-users mailing list: https://sourceforge.net/p/lammps/mailman/message/35456160/

**Comment by agiliopadua** [comment]
Dear Frank,
Thanks for letting me know. I've updated the script.
Agilio
