### ISSUE TITLE
Bug fftool OpenMM: impropers

### ISSUE THREAD

**Issue by kateryna-goloviznina** [agiliopadua/fftool#16]
Hello,

It seems that the order of atoms in the Improper in field.xml is not correct. OpenMM documentation says that the first atoms is the central one: "An improper torsion involves a central atom and three others that are bonded to it: atoms 2, 3, and 4 are all bonded to atom 1. ", while in our notation (because of Lammps) the central one is the third atom.

For example, in NO3- anion, the script gives
`<Improper class1="ON" class2="ON" class3="NO" class4="ON" c0="87.86400" c1="0.00000" c2="-87.86400" c3="0.00000" c4="0.00000" c5="0.00000" />`
while it should give
`<Improper class1="NO" class2="ON" class3="ON" class4="ON" c0="87.86400" c1="0.00000" c2="-87.86400" c3="0.00000" c4="0.00000" c5="0.00000" />`

Thank you,
Katya

**Comment by agiliopadua** [comment]
Fixed it, thanks Katya!
