### ISSUE TITLE
Newest commit creates incorrect pdb files with ilff

### ISSUE THREAD

**Issue by owluitar** [agiliopadua/fftool#5]
Master created config.pdb on the left, fftool-02/22/2019 on the right (runs in GROMACS directly)
![image](https://user-images.githubusercontent.com/8798763/86353450-d79a0680-bc2c-11ea-9e1f-ee99e9591ce8.png)

**Comment by owluitar** [comment]
created in both versions using:
 fftool 100 c8c1im.zmat 100 ntf2.zmat --rho 1.0 
packmol < pack.inp
 fftool 100 c8c1im.zmat 100 ntf2.zmat --rho 1.0 -g

Seems to be related to line 1971,1972,1974. When I change 

f.write('HETATM{0:5d} {1:4s} {2:**4**s}  {3:4d}    '\
                  '{4:8.3f}{5:8.3f}{6:8.3f}  1.00  0.00'\
s}\n'.format(i + 1, **atomic_symbol(at.name)[:4]**,
                                     sp.name[:**4**], nmol + 1,

to 

f.write('HETATM{0:5d} {1:4s} {2:**3**s}  {3:4d}    '\
                  '{4:8.3f}{5:8.3f}{6:8.3f}  1.00  0.00'\
s}\n'.format(i + 1, **at.name**,
                                     sp.name[:**3**], nmol + 1,

It produces the correct pdb (not sure whether this breaks anything else though).

**Comment by agiliopadua** [comment]
Thank you for this (I don't use gromacs myself). I'll revert to the old format.

**Comment by agiliopadua** [comment]
Could you please test?

**Comment by owluitar** [comment]
No it's not just an alignment problem, the atom types are only shown as atomic symbols in column 13 as opposed to topology file atom names such as C2, CS, etc. 

Example field.top: 
..
[ atomtypes ]                                                                                                                                                                        
; name  at.nr     mass   charge  ptype  sigma        epsilon                                                                                                                         NA          7  14.0070   0.1500      A  3.25000e-01  7.11280e-01                                                                                                                     CR          6  12.0110  -0.1100      A  3.55000e-01  2.92880e-01                                                                                                                     CW          6  12.0110  -0.1300      A  3.55000e-01  2.92880e-01                                                                                                                     C1          6  12.0110  -0.1700      A  3.50000e-01  2.76140e-01                                                                                                                     HCR         1   1.0080   0.2100      A  2.42000e-01  1.25520e-01 
....

There are multiple Carbon parameters
i.e. CW vs. C1, so the pdb file needs the atom names to be separate.

**Comment by agiliopadua** [comment]
Ok, got it, thanks. I've uploaded a new version.

**Comment by owluitar** [comment]
I'm sorry to bother again, but I didn't notice another correction is in the writing of the topology file. (I had correctly written topologies that were written by the previous fftool so I didn't notice).


To match the format between the .pdb and .top file, on line 1879-1881, if you change:

f.write('{0:5d}   {1:4s}  {2:5d}  {3:**6**s} {4:5s}  {5:4d}'\
'  {6:10.6f}\n'.format(i, at.name, 1,
sp.name[**:4**], **atomic_symbol(at.name)[:4]**, i, at.q))


to:

f.write('{0:5d}   {1:4s}  {2:5d}  {3:**5**s} {4:5s}  {5:4d}'\
'  {6:10.6f}\n'.format(i, at.name, 1,
sp.name[**0:3**], **at.name**, i, at.q))

It should fix everything. 

I was teaching a few students and one of them downloaded the most up to date version and it gave them an error for the pdb molecules not matching the topology. 

I have tested this fix on two different versions of GROMACS so far without problems.

**Comment by agiliopadua** [comment]
Hello,
No worries. My mistake, I thought the problem was in the pdf format. Thank you!
I’ve just uploaded a correct version.
